id: P009405
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:37:11.600667
source_metadata:
  id: bdr:W1KG10163
  title: རྒྱ་གླིང་། ༼དབུ་ཅན་བྲིས་མ།༽
  author: ''
  volumes:
    43212e915cb14a83b59c3084b6df78d3:
      image_group_id: I1KG10222
      title: ''
      volume_number: 1
      total_pages: 535
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
