id: IA6A950D3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:15:23+00:00'
last_modified: '2022-06-08T10:46:58.182851+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10163
  title: རྒྱ་གླིང་། ༼དབུ་ཅན་བྲིས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7CC1:
      image_group_id: I1KG10222
      title: ''
      total_pages: 535
      order: 1
      base_file: 7CC1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
